/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultCaret;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import message.Message;
import server.ChatInterface;

/**
 * Chat GUI.
 * 
 * @author Mickaël Turnel
 * @author Line Pouvaret
 */
public class ChatGUI extends javax.swing.JFrame {
    /**
     * Enumeration to set the state of the Chat GUI.
     */
    private enum State { CONNECTED, DISCONNECTED };
    
    /**
     * Registry for the communication with the chat server.
     */
    private Registry registry;
    
    /**
     * User.
     * 
     * @see User
     */
    private User user;
    
    /**
     * boolean to check is the user is connected
     */
    private boolean isConnected;
    
    /**
     * Creates new form ChatUI.
     */
    public ChatGUI() {
        registry = null;
        user = null;
        isConnected = false;
        
        initComponents();
        setState(State.DISCONNECTED);
        jDialogConnect.setTitle("Connection");
        
        DefaultCaret caret = (DefaultCaret)jTextPaneChat.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (isConnected) {
                    if (JOptionPane.showConfirmDialog(windowEvent.getWindow(), 
                            "You are still connected!\nAre you sure you want to exit?", "Connection still up", 
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                        jMenuItemDisconnectActionPerformed(null);
                    }
                }
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogConnect = new javax.swing.JDialog();
        jTextFieldPseudo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIPServer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonConnect = new javax.swing.JButton();
        jPasswordFieldServer = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSend = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTextPaneChat = new javax.swing.JTextPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemConnect = new javax.swing.JMenuItem();
        jMenuItemDisconnect = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSave = new javax.swing.JMenuItem();

        jDialogConnect.setResizable(false);

        jTextFieldPseudo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldConnectionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPseudoKeyReleased(evt);
            }
        });

        jLabel1.setText("Pseudo");

        jLabel2.setText("Server");

        jTextFieldIPServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldConnectionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPseudoKeyReleased(evt);
            }
        });

        jLabel3.setText("Password");

        jButtonConnect.setText("Connect");
        jButtonConnect.setEnabled(false);
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jPasswordFieldServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldConnectionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jDialogConnectLayout = new javax.swing.GroupLayout(jDialogConnect.getContentPane());
        jDialogConnect.getContentPane().setLayout(jDialogConnectLayout);
        jDialogConnectLayout.setHorizontalGroup(
            jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConnectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogConnectLayout.createSequentialGroup()
                        .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPseudo)
                            .addComponent(jTextFieldIPServer)
                            .addComponent(jPasswordFieldServer)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogConnectLayout.createSequentialGroup()
                        .addGap(0, 221, Short.MAX_VALUE)
                        .addComponent(jButtonConnect)))
                .addContainerGap())
        );
        jDialogConnectLayout.setVerticalGroup(
            jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConnectLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIPServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConnect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldSend.setEnabled(false);
        jTextFieldSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSendKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSendKeyReleased(evt);
            }
        });

        jButtonSend.setText("Send");
        jButtonSend.setEnabled(false);
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jTextPaneChat.setEditable(false);
        jScrollPane.setViewportView(jTextPaneChat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSend, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSend)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSend)
                    .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuFile.setText("File");

        jMenuItemConnect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemConnect.setText("Connect");
        jMenuItemConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConnectActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemConnect);

        jMenuItemDisconnect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDisconnect.setText("Disconnect");
        jMenuItemDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisconnectActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemDisconnect);
        jMenuFile.add(jSeparator1);

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSave.setText("Save conversation");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSave);

        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConnectActionPerformed
        if (!isConnected) {
            jDialogConnect.pack();
            jDialogConnect.setLocationRelativeTo(this);
            jDialogConnect.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Your first need to disconnect from current server.", "You are still connected!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemConnectActionPerformed

    private void jMenuItemDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisconnectActionPerformed
        if (isConnected) {
            try {
                ChatInterface chat = (ChatInterface) registry.lookup("Chat");
                chat.unregister(user.getId(), user.getPseudo(), "localhost");
                
                registry = null;
                user = null;
                isConnected = false;
                
                setState(State.DISCONNECTED);
                appendChat(new Message("", "", "Disconnected from \"" + jTextFieldIPServer.getText() + "\"...", Message.Type.APPLICATION), jTextPaneChat);
            } catch (RemoteException | NotBoundException ex) {
                appendChat(new Message("", "", "Error when disconnecting...\nReason : " + ex.getCause(), Message.Type.ERROR), jTextPaneChat);
            }
        } else {
            appendChat(new Message("", "", "You need to be connected to a server...", Message.Type.ERROR), jTextPaneChat);
        }
    }//GEN-LAST:event_jMenuItemDisconnectActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        JFileChooser jfc = new JFileChooser();
        int ret = jfc.showSaveDialog(this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            try {
                FileWriter f = new FileWriter(jfc.getSelectedFile());
                f.write(jTextPaneChat.getText());
                f.close();
                appendChat(new Message("", "", "File \"" + jfc.getSelectedFile().getName() + "\" saved...", Message.Type.APPLICATION), jTextPaneChat);
            } catch (IOException ex) {
                appendChat(new Message("", "", "Impossible to save \"" + jfc.getSelectedFile().getName() + "\"\nreason: " + ex.getCause(), Message.Type.ERROR), jTextPaneChat);
            }
        }
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        jDialogConnect.setVisible(false);
        
        try {
            registry = LocateRegistry.getRegistry(jTextFieldIPServer.getText());
            ChatInterface chat = (ChatInterface) registry.lookup("Chat");
            
            String id = chat.getUserId();
            String pseudo = jTextFieldPseudo.getText();
            String PasswordServer = jPasswordFieldServer.getText();
            
            appendChat(new Message("", "", "Connection to server \"" + jTextFieldIPServer.getText() + "\"...", Message.Type.APPLICATION), jTextPaneChat);
            
            user = new User(id, pseudo, jTextPaneChat);
            UserInterface u_stub = (UserInterface) UnicastRemoteObject.exportObject(user, 0);
            
            Registry regLocal = LocateRegistry.getRegistry();
            regLocal.rebind(id, u_stub);
            
            switch(chat.register(id, pseudo, "localhost", PasswordServer)) {
                case 0:
                    setState(State.CONNECTED);
                    isConnected = true;
                    jTextFieldSend.requestFocus();
                    break;
                case -1:
                    registry = null;
                    user = null;

                    appendChat(new Message("", "", "Wrong password for " + jTextFieldIPServer.getText() + "...", Message.Type.ERROR), jTextPaneChat);
                    break;
                case -2:
                    registry = null;
                    user = null;
                    
                    appendChat(new Message("", "", "Pseudo \"" + jTextFieldPseudo.getText() + "\" is already used, try again...", Message.Type.ERROR), jTextPaneChat);
                    break;
            }
        } catch (RemoteException | NotBoundException ex) {
            appendChat(new Message("", "", "Error when connecting...\nReason : " + ex.getCause(), Message.Type.ERROR), jTextPaneChat);
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        if (isConnected) {
            try {
                ChatInterface chat = (ChatInterface) registry.lookup("Chat");
                chat.sendMessage(new Message("", user.getPseudo(), jTextFieldSend.getText()));

                jTextFieldSend.setText("");
                jButtonSend.setEnabled(false);
            } catch (RemoteException | NotBoundException ex) {
                appendChat(new Message("", "", "Error when sending...\nReason : " + ex.getCause(), Message.Type.ERROR), jTextPaneChat);
            }
        } else {
            appendChat(new Message("", "", "You need to be connected to a server...", Message.Type.ERROR), jTextPaneChat);
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jTextFieldConnectionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConnectionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER 
                && !jTextFieldPseudo.getText().isEmpty()
                && !jTextFieldIPServer.getText().isEmpty()) {
            jButtonConnectActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldConnectionKeyPressed

    private void jTextFieldPseudoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPseudoKeyReleased
        if (jTextFieldPseudo.getText().isEmpty() || jTextFieldIPServer.getText().isEmpty()) {
            jButtonConnect.setEnabled(false);
        } else {
            jButtonConnect.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldPseudoKeyReleased

    private void jTextFieldSendKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSendKeyReleased
        if (jTextFieldSend.getText().isEmpty()) {
            jButtonSend.setEnabled(false);
        } else {
            jButtonSend.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldSendKeyReleased

    private void jTextFieldSendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSendKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER 
                && !jTextFieldSend.getText().isEmpty()) {
            jButtonSendActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldSendKeyPressed
    
    /**
     * Set the state of the Chat GUI.
     * 
     * @param s State to set.
     */
    private void setState(State s) {
        switch(s) {
            case CONNECTED:
                jTextFieldSend.setEnabled(true);
                break;
            case DISCONNECTED:
                jTextFieldSend.setEnabled(false);
                jButtonSend.setEnabled(false);
                break;
        }
    }
    
    /**
     * Add the message to the JTextPane send in parameter.
     * 
     * @param message Message to show.
     * @param output JTextPane to append.
     */
    public static void appendChat(Message message, JTextPane output) {
        if (message == null || output == null) {
            return;
        }
        
        StyledDocument doc = output.getStyledDocument();
        Style s = output.addStyle("Color", null);
        StyleConstants.setForeground(s, Color.GREEN);
        
        try {
            if (!output.getText().isEmpty()) {
                doc.insertString(doc.getLength(), "\n", null);
            }
            
            if (!message.getTime().equals("")) {
                doc.insertString(doc.getLength(), message.getTime() + " ", s);
            }
        } catch (BadLocationException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (message.getPseudo().startsWith("Wisp")) {
            StyleConstants.setForeground(s, Color.PINK);
        } else {
            StyleConstants.setForeground(s, Color.BLUE);
        }
        
        try {
            if (message.getTypeMessage() == Message.Type.MESSAGE) {
                doc.insertString(doc.getLength(), message.getPseudo() + " : ", s);
            }
        } catch (BadLocationException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        switch(message.getTypeMessage()) {
            case MESSAGE:
            case APPLICATION:
                StyleConstants.setForeground(s, Color.BLACK);
                break;
            case SYSTEM:
                StyleConstants.setForeground(s, Color.ORANGE);
                break;
            case ERROR:
                StyleConstants.setForeground(s, Color.RED);
                break;
        }
        
        try {
            doc.insertString(doc.getLength(), message.getMessage(), s);
        } catch (BadLocationException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JDialog jDialogConnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemConnect;
    private javax.swing.JMenuItem jMenuItemDisconnect;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldServer;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldIPServer;
    private javax.swing.JTextField jTextFieldPseudo;
    private javax.swing.JTextField jTextFieldSend;
    private javax.swing.JTextPane jTextPaneChat;
    // End of variables declaration//GEN-END:variables
}
